"""Initial migration

Revision ID: 1cc5ee61efcf
Revises: 
Create Date: 2026-05-03 08:37:02.507797

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1cc5ee61efcf'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blocking_reasons',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('hard_block', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('moderators',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('processed_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sender_service', sa.String(length=20), nullable=False),
    sa.Column('idempotency_key', sa.UUID(), nullable=False),
    sa.Column('response_cached', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sender_service', 'idempotency_key', name='uq_processed_events_sender_idempotency')
    )
    op.create_table('product_moderation',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('seller_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('queue_priority', sa.Integer(), nullable=False),
    sa.Column('total_active_quantity', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('json_before', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('json_after', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('blocking_reason_id', sa.UUID(), nullable=True),
    sa.Column('moderator_id', sa.UUID(), nullable=True),
    sa.Column('moderator_comment', sa.Text(), nullable=True),
    sa.Column('date_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('date_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('date_moderation', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('queue_priority BETWEEN 1 AND 4', name='ck_product_moderation_queue_priority'),
    sa.ForeignKeyConstraint(['blocking_reason_id'], ['blocking_reasons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_moderation_product_id'), 'product_moderation', ['product_id'], unique=True)
    op.create_index('ix_product_moderation_status_priority_updated', 'product_moderation', ['status', 'queue_priority', 'date_updated'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('moderator_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['moderator_id'], ['moderators.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_refresh_tokens_moderator_id'), 'refresh_tokens', ['moderator_id'], unique=False)
    op.create_table('field_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_moderation_id', sa.UUID(), nullable=False),
    sa.Column('field_name', sa.String(length=20), nullable=False),
    sa.Column('sku_id', sa.UUID(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['product_moderation_id'], ['product_moderation.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('field_reports')
    op.drop_index(op.f('ix_refresh_tokens_moderator_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index('ix_product_moderation_status_priority_updated', table_name='product_moderation')
    op.drop_index(op.f('ix_product_moderation_product_id'), table_name='product_moderation')
    op.drop_table('product_moderation')
    op.drop_table('processed_events')
    op.drop_table('moderators')
    op.drop_table('blocking_reasons')
    # ### end Alembic commands ###
